### ISSUE TITLE
Lab 04 Network Architecture weight initial

### ISSUE THREAD

**Issue by conlinwang** [2017-fall-DL-training-program/Reinforcement_Learning#2]
Dear TA,
in the spec of lab 04 First and second layer:
you wrote weight initial with He's weight init ?? what do you mean by He's weight init??

do you suggest that we use weight.data.normal_(0, 0.1)?

thank you

**Comment by BIGBALLON** [comment]
Hi, @conlinwang 

weight.data.normal_(0, 0.1) is ok in this code.
but sometimes we will use other init methods
(Random Normal, Truncated Normal,[ Glorot normal](http://jmlr.org/proceedings/papers/v9/glorot10a/glorot10a.pdf),[He normal](http://arxiv.org/abs/1502.01852) etc.)


## He normal initializer.

He's weight init means kaiming He([何恺明](http://kaiminghe.com/))'s weight initialization.
It is called He' weight in many frameworks, but called [kaiming_normal](http://pytorch.org/docs/0.3.0/nn.html?highlight=torch%20nn%20init%20kaiming_normal#torch.nn.init.kaiming_normal) in pytorch.

It draws samples from a truncated normal distribution 
centered on 0 with ``stddev = sqrt(2 / fan_in)`` 
where `` fan_in`` is the number of input units in the weight tensor.

**Comment by conlinwang** [comment]
thank you!!
