### ISSUE TITLE
About ReLU

### ISSUE THREAD

**Issue by yyrkoon27** [2017-fall-DL-training-program/Reinforcement_Learning#4]
Dear TA,

After your spec. modification, the current network looks like:
Linear -> ReLU -> Linear -> ReLU

The second ReLU seems strange because it may change the "best" action. 

For example, if the output of the second linear layer is (-0.7, -0.4) --> the best action is 1;
after ReLU it becomes (0, 0) --> the best action is 0 now.

Maybe my understanding is wrong. In any case, please help confirm this issue. Thank you very much!

**Comment by BIGBALLON** [comment]
Hello, @yyrkoon27  forget it.
It is [Linear -> ReLU -> Linear ]. not [Linear -> ReLU -> Linear -> ReLU].
I will update SPEC later.
Thanks a lot.
