### ISSUE TITLE
What is the physical meaning of phi of x?

### ISSUE THREAD

**Issue by bcpenggh** [2017-fall-DL-training-program/Reinforcement_Learning#5]
Dear TA,

In reference [1] and the pseudo code you provided in the handout, there is a function phi. Here is the definition in [1].
![2017-12-21_142412](https://user-images.githubusercontent.com/32902010/34243256-d797be7a-e65a-11e7-93f1-2a03c076ad3d.jpg)

And in the pseudo coed in [1], phi seems very similar to _s_.

![2017-12-21_142915](https://user-images.githubusercontent.com/32902010/34243608-8187a49e-e65c-11e7-82ac-e3f602850198.jpg)

What is the physical meaning of phi? And what is the meaning of the code in the red box in the figure above?

**Comment by BIGBALLON** [comment]
Hello, @bcpenggh  ,

Because sometimes the raw data can't be used as input directly(e.g. raw data is 256x224, but the input of our network is 128x128), so we need do some preprocess(resize, crop, RGB -> gray, etc.), it called phi of x.

In our Lab, Φ(x) = x, so you can ignore it directly.

**Comment by bcpenggh** [comment]
Got it! Thanks.
